#pragma once
#ifdef BUILDING_GENERATED_CODE
#define EXPORT_VAR __declspec(dllexport) extern
#define EXPORT_FUNC __declspec(dllexport)
#else
#define EXPORT_VAR __declspec(dllimport) extern
#define EXPORT_FUNC __declspec(dllimport)
#endif
// Standard C++ includes
#include <algorithm>
#include <chrono>
#include <iostream>
#include <random>

// Standard C includes
#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#define DT 1.00000000000000006e-01f
typedef float scalar;
#define SCALAR_MIN 1.175494351e-38f
#define SCALAR_MAX 3.402823466e+38f

#define TIME_MIN 1.175494351e-38f
#define TIME_MAX 3.402823466e+38f

// ------------------------------------------------------------------------
// bit tool macros
#define B(x,i) ((x) & (0x80000000 >> (i))) //!< Extract the bit at the specified position i from x
#define setB(x,i) x= ((x) | (0x80000000 >> (i))) //!< Set the bit at the specified position i in x to 1
#define delB(x,i) x= ((x) & (~(0x80000000 >> (i)))) //!< Set the bit at the specified position i in x to 0

extern "C" {
// ------------------------------------------------------------------------
// global variables
// ------------------------------------------------------------------------
EXPORT_VAR unsigned long long iT;
EXPORT_VAR float t;

// ------------------------------------------------------------------------
// timers
// ------------------------------------------------------------------------
EXPORT_VAR double initTime;
EXPORT_VAR double initSparseTime;
EXPORT_VAR double neuronUpdateTime;
EXPORT_VAR double presynapticUpdateTime;
EXPORT_VAR double postsynapticUpdateTime;
EXPORT_VAR double synapseDynamicsTime;
// ------------------------------------------------------------------------
// local neuron groups
// ------------------------------------------------------------------------
#define spikeCount_Pop1 glbSpkCntPop1[0]
#define spike_Pop1 glbSpkPop1
#define glbSpkShiftPop1 0

EXPORT_VAR unsigned int* glbSpkCntPop1;
EXPORT_VAR unsigned int* glbSpkPop1;
EXPORT_VAR scalar* VPop1;
EXPORT_VAR scalar* mPop1;
EXPORT_VAR scalar* hPop1;
EXPORT_VAR scalar* nPop1;

// ------------------------------------------------------------------------
// custom update variables
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// pre and postsynaptic variables
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// synapse connectivity
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// synapse variables
// ------------------------------------------------------------------------

EXPORT_FUNC void pushPop1SpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullPop1SpikesFromDevice();
EXPORT_FUNC void pushPop1CurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullPop1CurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getPop1CurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getPop1CurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushVPop1ToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullVPop1FromDevice();
EXPORT_FUNC void pushCurrentVPop1ToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentVPop1FromDevice();
EXPORT_FUNC scalar* getCurrentVPop1(unsigned int batch = 0); 
EXPORT_FUNC void pushmPop1ToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmPop1FromDevice();
EXPORT_FUNC void pushCurrentmPop1ToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmPop1FromDevice();
EXPORT_FUNC scalar* getCurrentmPop1(unsigned int batch = 0); 
EXPORT_FUNC void pushhPop1ToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullhPop1FromDevice();
EXPORT_FUNC void pushCurrenthPop1ToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrenthPop1FromDevice();
EXPORT_FUNC scalar* getCurrenthPop1(unsigned int batch = 0); 
EXPORT_FUNC void pushnPop1ToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullnPop1FromDevice();
EXPORT_FUNC void pushCurrentnPop1ToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentnPop1FromDevice();
EXPORT_FUNC scalar* getCurrentnPop1(unsigned int batch = 0); 
EXPORT_FUNC void pushPop1StateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullPop1StateFromDevice();
// Runner functions
EXPORT_FUNC void copyStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void copyConnectivityToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void copyStateFromDevice();
EXPORT_FUNC void copyCurrentSpikesFromDevice();
EXPORT_FUNC void copyCurrentSpikeEventsFromDevice();
EXPORT_FUNC void allocateMem();
EXPORT_FUNC void freeMem();
EXPORT_FUNC size_t getFreeDeviceMemBytes();
EXPORT_FUNC void stepTime();

// Functions generated by backend
EXPORT_FUNC void updateNeurons(float t); 
EXPORT_FUNC void updateSynapses(float t);
EXPORT_FUNC void initialize();
EXPORT_FUNC void initializeSparse();
}  // extern "C"
